# Упражнения "Работа с тензорами в PyTorch"

Задание 1. Импортируйте PyTorch и посмотрите версию.

In [1]:
import torch
print(torch.__version__)

2.9.0+cpu


Задание 2. Создайте одномерный тензор чисел от 0 до 9.

Желаемый результат:

> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
A = torch.tensor(
    # Передаётся объект, который нужно превратить в тензор.
    [0,1, 2, 3, 4,5,6,7,8,9],
    # Можно вручную указать, какого типа должны быть элементы тензора

)
A


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Задание 3. Для тензора, созданного в задании 2, выведите


*   тип элементов
*   размер
*   количество размерностей



In [3]:
print(
    f"Вектор:\n{A}",
    f"Какого типа элементы вектора   --> {A.dtype}",
    f"Размеры вектора                --> {A.shape}",
    f"Количество размерностей        --> {A.dim()}",
    sep="\n\n",
)


Вектор:
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Какого типа элементы вектора   --> torch.int64

Размеры вектора                --> torch.Size([10])

Количество размерностей        --> 1


Задание 4. Разделите тензор из задания 2 на две половины (левую - начало тензора и правую - его конец). Выведите обе эти половины.

In [4]:
print(A[:5],A[5:])


tensor([0, 1, 2, 3, 4]) tensor([5, 6, 7, 8, 9])


Задание 5. Создайте вещественный массив размером $3 \times 4$, в котором все элементы равны 1.

In [5]:
# Создать тензор с заданными размерами, состоящий из единиц.
torch.ones(3, 4)


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Задание 6. Создайте логический массив размером $5 \times 2$, в котором все элементы равны True.

In [6]:
torch.ones(5, 2,dtype=torch.bool)



tensor([[True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True]])

Задание 7. Создайте одномерный тензор с последовательностью вещественных чисел от 1 до 15 включительно, в котором каждый следующий элемент отличается от предыдущего на 0.5

In [7]:
torch.arange(1, 15.5, 0.5, )


tensor([ 1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,  4.0000,  4.5000,
         5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,  8.0000,  8.5000,
         9.0000,  9.5000, 10.0000, 10.5000, 11.0000, 11.5000, 12.0000, 12.5000,
        13.0000, 13.5000, 14.0000, 14.5000, 15.0000])

Задание 8. Создайте одномерный тензор, в котором ровно 20 значений. Первой значение 1, последнее значение 10, а расстояние между каждыми двумя соседними элементами одинаково.

In [8]:
torch.arange(1, 10.5, 0.5, )


tensor([ 1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,  4.0000,  4.5000,
         5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,  8.0000,  8.5000,
         9.0000,  9.5000, 10.0000])

Задание 9. Создайте двумерный тензор случайных вещественных значений размером $4 \times 3$ из равномерного распределения на полуинтервале [0, 1).

In [9]:
torch.randn(4, 3, )


tensor([[ 0.4512, -0.5350,  0.7048],
        [-0.3137, -0.0842,  0.5708],
        [-0.8612,  0.4297, -0.1955],
        [-0.6317, -1.6294,  0.6569]])

Задание 10. Создайте одномерный тензор 100 случайных "школьных оценок", а именно целых значений из промежутка от 3 до 5 включительно.

In [10]:
C = torch.randint(
    3,      # low - минимальное значение.
    6,       # high - 1 + максимальное значение.
    (100,),  # size - размерности тензора.
)
C


tensor([5, 3, 3, 4, 5, 4, 4, 3, 5, 5, 4, 4, 5, 3, 3, 4, 3, 5, 3, 5, 4, 5, 5, 4,
        3, 4, 5, 3, 4, 3, 5, 4, 3, 4, 4, 5, 4, 5, 4, 5, 3, 4, 5, 4, 5, 3, 4, 4,
        3, 5, 4, 5, 5, 4, 5, 5, 3, 5, 4, 5, 5, 5, 3, 4, 5, 4, 5, 4, 5, 4, 5, 5,
        5, 4, 5, 4, 4, 4, 3, 4, 5, 4, 3, 5, 5, 3, 3, 5, 5, 4, 3, 3, 3, 4, 5, 5,
        5, 3, 5, 3])

Задание 11. Для тензора "школьных отенок", созданного в задании 10, посчитайте и выведите минимум, максимум и среднее арифметическое.

In [11]:
print(
    f"Максимальное значение:\n{C.max()}",
    f"Минимальное значение:\n{C.min()}",
    f"Среднее арифметическое элементов:\n{C.float().mean()}",
    sep="\n\n",
)


Максимальное значение:
5

Минимальное значение:
3

Среднее арифметическое элементов:
4.159999847412109


Задание 12. Создайте создайте булеву маску для массива "школьных оценок" из задания 10, в которой True будет стоять для первых 5 оценок и для последних 5 оценок, а остальные значения будут False.

In [12]:
bool_mask = torch.zeros(len(C), dtype=torch.bool)  # Все False
bool_mask[:5] = True    # Первые 5 → True
bool_mask[-5:] = True   # Последние 5 → True
print(bool_mask)




tensor([ True,  True,  True,  True,  True, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False,  True,  True,  True,  True,  True])


Задание 13. Отфильтруйте тензор "школьных оценок", созданный в задании 10, с помощью маски, созданной в задании 12, оставив тем самым только первые и последние пять оценок.

In [13]:
first_five = bool_mask[:5]
last_five = bool_mask[-5:]

# Объединяем в один массив
combined = torch.cat([first_five, last_five])

print("Объединенный массив (первые 5 + последние 5):")
print(combined)


Объединенный массив (первые 5 + последние 5):
tensor([True, True, True, True, True, True, True, True, True, True])


Задание 14. Создайте маску для тензора "школьных оценок", в которой для каждой "пятерки" будет стоять True, а для остальных значений будет стоять False.

In [14]:
P = torch.tensor(C)
for i in range(0,100):
  if P[i]==5:
    P[i]==1
  else:
    P[i]=0
P1 = torch.tensor(P,dtype=torch.bool)
print(P1)

tensor([ True, False, False, False,  True, False, False, False,  True,  True,
        False, False,  True, False, False, False, False,  True, False,  True,
        False,  True,  True, False, False, False,  True, False, False, False,
         True, False, False, False, False,  True, False,  True, False,  True,
        False, False,  True, False,  True, False, False, False, False,  True,
        False,  True,  True, False,  True,  True, False,  True, False,  True,
         True,  True, False, False,  True, False,  True, False,  True, False,
         True,  True,  True, False,  True, False, False, False, False, False,
         True, False, False,  True,  True, False, False,  True,  True, False,
        False, False, False, False,  True,  True,  True, False,  True, False])


/tmp/ipython-input-3938352282.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  P = torch.tensor(C)
/tmp/ipython-input-3938352282.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  P1 = torch.tensor(P,dtype=torch.bool)


Задание 15. Извлеките все "пятерки" из тензора "школьных отенок", созданного в задании 10, и занесите их в новый тензор.


In [15]:
P2 = torch.tensor(C)#создание нового тензора P3 является копией С
five=[]#пустой список
for i in range(len(P2)):
  if P2[i]==5:
    five.append(5)#добавляем только пятёрки
P3 = torch.tensor(five)#создание тензора из списка
print(P3)

tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])


/tmp/ipython-input-3379269206.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  P2 = torch.tensor(C)#создание нового тензора P3 является копией С


Задание 16. Преобразуйте тензор "школьных оценок" в двумерный тензор с 5 строками размером $5 \times 20$.


In [16]:
print(
    f"Изменять размерность:\n{C.reshape(5, 20)}",
    sep="\n\n",
)


Изменять размерность:
tensor([[5, 3, 3, 4, 5, 4, 4, 3, 5, 5, 4, 4, 5, 3, 3, 4, 3, 5, 3, 5],
        [4, 5, 5, 4, 3, 4, 5, 3, 4, 3, 5, 4, 3, 4, 4, 5, 4, 5, 4, 5],
        [3, 4, 5, 4, 5, 3, 4, 4, 3, 5, 4, 5, 5, 4, 5, 5, 3, 5, 4, 5],
        [5, 5, 3, 4, 5, 4, 5, 4, 5, 4, 5, 5, 5, 4, 5, 4, 4, 4, 3, 4],
        [5, 4, 3, 5, 5, 3, 3, 5, 5, 4, 3, 3, 3, 4, 5, 5, 5, 3, 5, 3]])


Задание 17. Выполните стыковку тензоров a и b по вертикали.

Вход:

> a = torch.arange(2, 10, 2).reshape(2, -1)

> b = torch.repeat(1, 10).reshape(2, -1)

Желаемый результат: новый тензор размером $4 \times 5$.


In [17]:
a = torch.arange(10).reshape(2, -1)
b = torch.ones(10).reshape(2, -1)
S = torch.cat([a, b], dim=0)#объединение по строкам (dim=0 вертикально)

print(
    f"Объединять вдоль существующей оси:\n{S}",
    f"Изменять размерность:\n{S.reshape(4, 5)}",
    sep="\n\n",

)

Объединять вдоль существующей оси:
tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

Изменять размерность:
tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


Задание 18. Выполните стыковку тензоров a и b по горизонтали.

Вход:

a = torch.arange(2, 10, 2).reshape(2, -1)

b = torch.repeat(1, 10).reshape(2, -1)

Желаемый результат: новый тензор размером 2 x 10

In [18]:
a = torch.arange(2,10,2).reshape(2, -1)
b = torch.ones(1,10).reshape(2, -1)
V = torch.cat([a, b], dim=1)
print(V)

tensor([[2., 4., 1., 1., 1., 1., 1.],
        [6., 8., 1., 1., 1., 1., 1.]])


Задание 19. Получите все элементы от 5 до 10 в тензоре a.

Вход:

> a = torch.tensor([2, 6, 1, 9, 10, 3, 27])

Желаемый результат:

> tensor([6, 9, 10])

In [19]:
#a = torch.tensor([2, 6, 1, 9, 10, 3, 27])
#Y=[]
#Z=[5,6,7,8,9,10]
#for i in range(len(a)):
#  if a[i] in Z:
#    Y.append(a[i])
#print(Y)
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])
mask = (a >= 5) & (a <= 10)  # маска 5 до 10
result = a[mask]  # Применение маски
print(result)

tensor([ 6,  9, 10])


Задание 20. Вывести первую строку матрицы из задания 18.

In [20]:
print(V[0])

tensor([2., 4., 1., 1., 1., 1., 1.])


Задание 21. Вывести последний столбец матрицы из задания 17.

In [21]:
print(S)
print(S[:,4])

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([4., 9., 1., 1.])


Задание 22. Вывести центральную часть матрицы из задания 17 (размерностью $2 \times 3$).

In [22]:
print(S[1:3, 1:4]) # 1:3 строки 1:4 столбцы


tensor([[6., 7., 8.],
        [1., 1., 1.]])


Задание 23. Вставить в двумерный терзор из задания 17 строку из минимального элемента перед первой строкой.

In [23]:
M=S.min()
strokaizM=torch.full((1, S.shape[1]), M)
T=torch.cat([strokaizM, S], dim=0)
print(
    f"Объединять вдоль существующей оси:\n{torch.cat([strokaizM, S], dim=0)}",
)

Объединять вдоль существующей оси:
tensor([[0., 0., 0., 0., 0.],
        [0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


Задание 24.	В тензоре, полученном при выполнении задания 23, каждый элемент заменить его корнем квадратным.

In [24]:
print(

    f"Значения по корнем квадратным:\n{T.sqrt()}",

)

Значения по корнем квадратным:
tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 1.0000, 1.4142, 1.7321, 2.0000],
        [2.2361, 2.4495, 2.6458, 2.8284, 3.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000]])


Задание 25.	Заменить в тензоре из задания 18 все значения, кратные 3 или 2 на число 1, а остальные – оставить без изменений.

In [25]:
R=torch.tensor(V[0])
for i in range(len(R)):
  if R[i]%3==0 or R[i]%2==0:
    R[i]=1
R1=torch.tensor(V[1])
for i in range(len(R1)):
  if R1[i]%3==0 or R1[i]%2==0:
    R1[i]=1
R2=torch.cat([R, R1], dim=0)
print(R2.reshape(2, 7))

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])


/tmp/ipython-input-3139666441.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  R=torch.tensor(V[0])
/tmp/ipython-input-3139666441.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  R1=torch.tensor(V[1])
